version: '3.1'

services:

  dfunction:
    image: rodezee/dfunction:0.0.1
    #build: .
    restart: always
    environment:
      COOKIE_SECRET: V2OPWuh8RaS6ewUGL580qCr
    ports:
      - 1080:1080
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./app:/app
    working_dir: /app

